export const grapesKo = {
  assetManager: {
    addButton: '이미지 추가',
    inputPlaceholder: 'http://path/to/image.jpg',
    modalTitle: '에셋 매니저',
    uploadTitle: '여기에 파일을 드롭하거나 클릭하여 업로드하세요',
  },
  blockManager: {
    labels: {
      // Categories
      Layout: '레이아웃',
      Sections: '섹션',
      Profiles: '프로필',
      Information: '정보/안내',
      Elements: '요소',
      Forms: '폼 요소',
      Basic: '기본',
    },
    categories: {
      Layout: '레이아웃',
      Sections: '섹션',
      Profiles: '프로필',
      Information: '정보/안내',
      Elements: '요소',
      Forms: '폼 요소',
      Basic: '기본',
    },
  },
  domComponents: {
    names: {
      '': '요소',
      wrapper: '본문',
      text: '텍스트',
      comment: '주석',
      image: '이미지',
      video: '비디오',
      label: '라벨',
      link: '링크',
      map: '지도',
      tfoot: '표 바닥글',
      tbody: '표 본문',
      thead: '표 머리글',
      table: '표',
      row: '행',
      cell: '열',
      input: '입력창',
      select: '선택창',
      checkbox: '체크박스',
      radio: '라디오 버튼',
      button: '버튼',
      form: '폼',
    },
  },
  deviceManager: {
    device: '기기',
    devices: {
      desktop: '데스크탑',
      tablet: '태블릿',
      mobileLandscape: '모바일 가로',
      mobilePortrait: '모바일 세로',
    },
  },
  panels: {
    buttons: {
      titles: {
        preview: '미리보기',
        fullscreen: '전체화면',
        'sw-visibility': '구성요소 보기',
        'export-template': '코드 보기',
        'open-sm': '스타일 에디터',
        'open-tm': '레이어',
        'open-layers': '레이어',
        'open-blocks': '블록 추가',
      },
    },
  },
  selectorManager: {
    label: '클래스',
    selected: '선택됨',
    emptyState: '- 클래스 없음 -',
    addPlaceholder: '클래스 이름 입력...',
  },
  styleManager: {
    emptyState: '수정할 요소를 선택하세요',
    sectors: {
      general: '일반',
      layout: '레이아웃',
      typography: '타이포그래피',
      decorations: '장식',
      extra: '추가 설정',
      flex: '플렉스박스',
      dimension: '크기 및 간격',
    },
    properties: {
      float: '플로트',
      display: '디스플레이',
      position: '위치',
      top: '상단',
      right: '우측',
      left: '좌측',
      bottom: '하단',
      width: '너비',
      height: '높이',
      'max-width': '최대 너비',
      'max-height': '최대 높이',
      margin: '바깥 여백',
      padding: '안쪽 여백',
      'font-family': '글꼴',
      'font-size': '글꼴 크기',
      'font-weight': '글꼴 두께',
      'letter-spacing': '자간',
      color: '글자 색상',
      'line-height': '줄 간격',
      'text-align': '정렬',
      'text-shadow': '글자 그림자',
      'background-color': '배경 색상',
      'background-image': '배경 이미지',
      'background-repeat': '배경 반복',
      'background-attachment': '배경 고정',
      'background-position': '배경 위치',
      'background-size': '배경 크기',
      'border-radius': '테두리 곡률',
      'border-top-left-radius': '좌상단 곡률',
      'border-top-right-radius': '우상단 곡률',
      'border-bottom-left-radius': '좌하단 곡률',
      'border-bottom-right-radius': '우하단 곡률',
      border: '테두리',
      'border-width': '테두리 두께',
      'border-style': '테두리 스타일',
      'border-color': '테두리 색상',
      'box-shadow': '박스 그림자',
      opacity: '투명도',
      transition: '트랜지션',
      transform: '트랜스폼',
    },
  },
  traitManager: {
    emptyState: '수정할 요소를 선택하세요',
    label: '속성 설정',
    traits: {
      labels: {
        id: 'ID',
        alt: '대체 텍스트',
        title: '제목',
        href: '링크 주소',
        target: '대상',
        name: '이름',
        placeholder: '플레이스홀더',
        value: '기본값',
        required: '필수 여부',
        type: '타입',
        options: '옵션',
        src: '소스 URL',
      },
      attributes: {
        type: {
          options: {
            text: '텍스트',
            email: '이메일',
            password: '비밀번호',
            number: '숫자',
            date: '날짜',
            tel: '전화번호',
            checkbox: '체크박스',
            radio: '라디오',
          }
        }
      }
    },
  },
};
